[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; 针对你板子上 N16R8 丝印的专属配置：开启 16MB 闪存和 8MB PSRAM
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

; 波特率保持一致
monitor_speed = 115200

; 强制锁定：绝对不使用左侧原生 USB 作为串口，把日志死死绑在右侧 COM 口上
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=0

; RGB 驱动库
lib_deps = 
    adafruit/Adafruit NeoPixel@^1.15.4