[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

;开启 16MB 闪存和 8MB PSRAM
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

; 波特率
monitor_speed = 115200

; 使用右侧type-c口作为串口输出口
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D BOARD_HAS_PSRAM

upload_protocol = espota

; 注意：这里的名字必须和你代码里 clientId 动态生成的名字完全一致
; 如果你的 clientId 是 ESP32S3-E83DC1FA71BC
; 如果远程ota失败，请关闭网络防火墙尝试，否则请使用mqttx输出的IP替换下方地址
;upload_port = 10.167.44.13

upload_port = ESP32S3-E83DC1FA71BC.local

upload_flags =
   --auth=admin123

; 离线缓存区
board_build.filesystem = littlefs

; 驱动库
lib_deps = 
    adafruit/Adafruit NeoPixel@^1.15.4  ; 板载RGB驱动
    knolleary/PubSubClient@^2.8       ; 最经典的 C++ MQTT 库
    bblanchon/ArduinoJson@^6.21.3     ; 极其高效的 C++ JSON 序列化库